### ISSUE TITLE
(v1.1.0.60) Blacklist seems to be ignored

### ISSUE THREAD

**Issue by GuestJim** [GPUOpen-Tools/OCAT#26]
Also observed with the [(v1.1.0.60) Single csv made when recording All Processes](https://github.com/GPUOpen-Tools/OCAT/issues/25) issue is that some blacklisted executables will still be recorded. I have seen explorer.exe, OCAT.exe, and the Desktop Window Manager all being recorded, despite being in the blacklist. The DWM is also weird because it is not named but by looking at the PID I can see it is dwm.exe being recorded when it should not be.
Repro steps
1. on version 1.1.0.60 check Record performance for all processes
2. examine the blacklist file and possibly add some new entries
3. make a recording and observe that some applications are still being recorded
It is not consistent in recording explorer.exe or OCAT.exe, but dwm (the label is empty but the PID matches) is being recorded every time for me. These entries do also appear in the perf_summary.csv file.

**Comment by amddb** [comment]
Hey @GuestJim in order to keep up with the PresentMon releases, I had to remove our changes from PresentMon source code. At the moment I am only calling into PresentMon with the same constraints as with command line options. As there is no blacklist functionality in PresentMon, I can't do anything about that - sorry :(. 

However you could suggest to add a blacklist here: https://github.com/GameTechDev/PresentMon
If such a feature is added to PresentMon, we can add it to OCAT easily.

In the meantime: Would it be helpful, if I would remove the blacklisted processes from the summary file?

**Comment by GuestJim** [comment]
Actually I think removing blacklisted processes from the summary would be an issue. That means the blacklist works in one of two places, which could confuse people. I kind of feel it would be better to essentially remove the blacklist altogether, until PresentMon can support it.
Just had an idea though; could it be possible to add a feature to OCAT to clean up the already made CSVs, removing blacklisted items? That way the blacklist still has a purpose until PresentMon may get the feature.

**Comment by amddb** [comment]
We can't remove the blacklist completely, as this is mostly a tool to workaround crashing other executables while trying to globally inject the overlay. 

However I think I will implement your second proposal. Removing processes that are on the blacklist from the created files shouldn't be an issue.

**Comment by GuestJim** [comment]
Excellent!

**Comment by rys** [comment]
Completely rewritten blacklist handling in 4edb7fa74425e8a22a952f2fb2d83778674db27a
