### ISSUE TITLE
This does not work at all!

### ISSUE THREAD

**Issue by LordRampantHump** [GPUOpen-Tools/OCAT#34]
I tried 7 games in my steam lib and this did not show overlay at all. The only thing i could get the overlay on was obs!

**Comment by aurolou** [comment]
Hi,

may I ask which version you tried? You can get the most current version [here](https://ci.appveyor.com/api/buildjobs/xpgfuwdrpqbdf745/artifacts/OCAT_1.1.0.125.exe). Could you please try this one out? We made a couple of changes and bug fixes since the last official release. If it still doesn't show any overlay, could you please describe the steps to reproduce your issue? Thanks! :)

**Comment by rys** [comment]
User didn’t follow up with more information after 9 months and we’ve improved compatibility a lot since then. Closing.
