### ISSUE TITLE
Fps drop in Trial evolution gold edition

### ISSUE THREAD

**Issue by Arias800** [GPUOpen-Tools/OCAT#36]
I have a lot of fps drop in Trial Evolution Gold Edition when i have OCAT open do you have any ideas why it's happen ?
My spec : 
CPU : I5-6300HQ 2.30Ghz
Ram : 8Gb
GPU : Nvidia gtx 1060 6gb
Os : Windows April Update 64bits

**Comment by aurolou** [comment]
OCAT does introduce some overhead which can cause a change in the fps rate. If you only want to get the recording files, you can also disable the overlay hook and see if this makes a difference. E.g. start OCAT, start your game with the overlay setting set to disabled, press the recording hotkey.

Further, which version did you use? We made significant changes since the last release - so you could try out the latest [version](https://ci.appveyor.com/api/buildjobs/hd7343lwk4s6e7fs/artifacts/OCAT_1.1.0.138.exe).

**Comment by Arias800** [comment]
Fix with the last release thanks
