### ISSUE TITLE
Assassin’s Creed Odyssey doesn't start when overlay is active

### ISSUE THREAD

**Issue by DevTechProfile** [GPUOpen-Tools/OCAT#47]
Version: 1.2.0.167
Same behaviour with GeForce 1080 Ti and AMD Vega 64. Overlay must be deactivated to start the game.

**Comment by aurolou** [comment]
Seems like this bug is related to UPlays anti-profiling mechanism. So the hooking for the overlay works in principle, but it gets stuck during the swapchain creation or, when hooking directly into the present call, it stucks there. This relates to the known issue, that the overlay doesn't work with UPlay games, sadly :( Sorry about that.

**Comment by DevTechProfile** [comment]
OK, thanks anyway!

**Comment by Taxxor90** [comment]
I just testet AC Odyssey with OCAT an in my case the game runs just fine, benchmarking also works and the numbers seem to fit.

The only issue is that the overlay won't show at all.

**Comment by rys** [comment]
Closing due to `wontfix` because of UPlay.
