### ISSUE TITLE
Overlay shows double the FPS with Shadow of the Tomb Raider DX12

### ISSUE THREAD

**Issue by Taxxor90** [GPUOpen-Tools/OCAT#49]
With Shadow of the TombRaider in DX11 mode, everything works fine.
The Overlay in the main menu states around 65fps, the bench summary states 64.7 average fps.

With DX12 however, the overlay states around 110fps. After the bench, the numbers on the overlay also stated 109.5 average fps, but the summary file states 55.6 average fps.

I first thought there's something wrong with the benchmark logging in DX12, but logging with FRAPS and Afterburner showed the fps are really around 55.

So the logging worked fine, it's just the overlay that shows double the framerate.

It's not a general DX12 problem though, with Battlefront 2 the numbers in the overlay match the log.

**Comment by aurolou** [comment]
I know in the current release there is an issue with showing double FPS in the overlay on some games, e.g. Rise of the Tomb Raider, it should be fixed in this [version](https://ci.appveyor.com/api/buildjobs/5e2i8mq29f17g626/artifacts/OCAT_1.2.0.185.exe). Do you mind checking if it also solves your issue? If it still persists, please let me know and I have a look.

**Comment by Taxxor90** [comment]
Yes the problem was fixed with the new version.

**Comment by aurolou** [comment]
Great, thanks for confirming.
