### ISSUE TITLE
"RegisterHotKey failed" message appears on startup

### ISSUE THREAD

**Issue by Reedbeta** [GPUOpen-Tools/ocat#75]
When launching OCAT 1.4.242, I receive the popup message:

>RegisterHotKey failed, F12 is a reserved key and cannot be used as hotkey 1409

After clicking through this, the app functions normally, although the Capture hotkey is undefined. (And if I redefine it to something else, the error message no longer appears.)

**Comment by aurolou** [comment]
Thanks for the report. It should fail completely - I will fix this.

**Comment by aurolou** [comment]
I should learn reading properly :) I thought capturing still works with F12, even it says Capture hotkey is undefined. The expected behavior is indeed as you described: F12 cannot be used as a hotkey anymore, so an error message will pop up in that case and the hotkey will be undefined. I will add to the message the urge to choose a different hotkey. ALT + F4 will also fail, btw - this is expected too.
